<?php

$MIN_HASH_RATE = $_POST['MIN_HASH_RATE'];
$MAX_HASH_RATE = $_POST['MAX_HASH_RATE'];
$HASH_RATE_VALUE = $_POST['HASH_RATE_VALUE'];
$HASH_RATE_STEP = $_POST['HASH_RATE_STEP'];
$HASH_RATE_COEF = $_POST['HASH_RATE_COEF'];
$HASH_RATE_MULTIPLIER = $_POST['HASH_RATE_MULTIPLIER'];
$MIN_POWER = $_POST['MIN_POWER'];
$MAX_POWER = $_POST['MAX_POWER'];
$POWER_VALUE = $_POST['POWER_VALUE'];
$POWER_STEP = $_POST['POWER_STEP'];
$POWER_COEF = $_POST['POWER_COEF'];
$POWER_MULTIPLIER = $_POST['POWER_MULTIPLIER'];

file_put_contents(
    '../assets/js/calc-settings.js',
    "var MIN_HASH_RATE = $MIN_HASH_RATE;\n"
    ."var MAX_HASH_RATE = $MAX_HASH_RATE;\n"
    ."var HASH_RATE_VALUE = $HASH_RATE_VALUE;\n"
    ."var HASH_RATE_STEP = $HASH_RATE_STEP;\n"
    ."var HASH_RATE_COEF = '$HASH_RATE_COEF';\n"
    ."var HASH_RATE_MULTIPLIER = $HASH_RATE_MULTIPLIER;\n"
    ."var MIN_POWER = $MIN_POWER;\n"
    ."var MAX_POWER = $MAX_POWER;\n"
    ."var POWER_VALUE = $POWER_VALUE;\n"
    ."var POWER_STEP = $POWER_STEP;\n"
    ."var POWER_COEF = '$POWER_COEF';\n"
    ."var POWER_MULTIPLIER = $POWER_MULTIPLIER;\n"
);
header('location: ../#section-calculator');
